# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Phan Uy Binh - A Web Developer
email: uybinh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Phan Uy Binh - A Web Developer - Ruby Rails JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "uybinh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: uybinh
github_username:  uybinh

# author
author:
  name: Phan Uy Binh
  url: https://uybinh.com
  email: uybinh@gmail.com

# Build settings
markdown: kramdown
# theme: minima

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5













# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
